basePath: /api/v1
definitions:
  app_user.AvatarChooseInput:
    properties:
      avatar:
        type: string
    type: object
  app_user.NumberInput:
    properties:
      number:
        type: string
    required:
    - number
    type: object
  app_user.RefreshInput:
    properties:
      refresh:
        type: string
    required:
    - refresh
    type: object
host: localhost:1111
info:
  contact: {}
  description: Pedarkharj project
  title: Pedarkharj
  version: 1.0.0
paths:
  /devices/logout:
    post:
      consumes:
      - application/json
      description: Logout current user device
      produces:
      - application/json
      responses:
        "200":
          description: Successfully logged out
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Logout current device
      tags:
      - devices
  /devices/logout-all:
    post:
      consumes:
      - application/json
      description: Logout all user devices
      produces:
      - application/json
      responses:
        "200":
          description: Successfully logged out from all devices
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Logout all user devices
      tags:
      - devices
  /expenses:
    post:
      consumes:
      - application/json
      description: create new expense.
      parameters:
      - description: expense name
        in: body
        name: name
        required: true
        schema:
          type: string
      - description: expense description
        in: body
        name: description
        required: true
        schema:
          type: string
      - description: 'creditors key value list: phone number is key and credit amount
          is value'
        in: body
        name: creditors
        required: true
        schema:
          additionalProperties:
            type: integer
          type: object
      - description: list of debtors phone number
        example: '"["+989123456786", "+989123456787"]"'
        in: body
        name: debtors
        required: true
        schema:
          items:
            type: string
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: Ok
        "400":
          description: 'BadRequest:<br>code=invalid_field: a field is invalid'
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      tags:
      - expenses
  /users/avatar:
    get:
      consumes:
      - application/json
      description: Get list of available avatar images
      produces:
      - application/json
      responses:
        "200":
          description: List of avatars
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Get available avatars
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Set user's avatar image
      parameters:
      - description: Avatar URL
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/app_user.AvatarChooseInput'
      produces:
      - application/json
      responses:
        "200":
          description: Avatar updated
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid input
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Choose user avatar
      tags:
      - users
  /users/check-number:
    post:
      consumes:
      - application/json
      description: Check if phone number is registered
      parameters:
      - description: Phone number to check
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/app_user.NumberInput'
      produces:
      - application/json
      responses:
        "200":
          description: Number status
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid input
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Check number existence
      tags:
      - users
  /users/info:
    get:
      consumes:
      - application/json
      description: Get authenticated user's profile (Authentication Required)
      produces:
      - application/json
      responses:
        "200":
          description: User information
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Get user information
      tags:
      - users
  /users/login:
    post:
      consumes:
      - application/json
      description: login user with number and password
      parameters:
      - description: phone number
        example: "+98123456789"
        in: body
        name: number
        required: true
        schema:
          type: string
      - description: Password
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: 'BadRequest:<br>code=invalid_field: a field is invalid'
        "500":
          description: Internal Server Error
      tags:
      - users
  /users/refresh:
    post:
      consumes:
      - application/json
      description: Get new access token using refresh token
      parameters:
      - description: Refresh token
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/app_user.RefreshInput'
      produces:
      - application/json
      responses:
        "200":
          description: New access token
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid token
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Refresh access token
      tags:
      - users
  /users/reset-password:
    post:
      consumes:
      - application/json
      description: Reset user password.
      parameters:
      - description: phone number
        example: "+98123456789"
        in: body
        name: number
        required: true
        schema:
          type: string
      - description: Token
        in: body
        name: token
        required: true
        schema:
          type: string
      - description: Password
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: 'BadRequest:<br>code=verify_number_first: User Must be verify
            number first<br>code=invalid_field: a field is invalid'
        "500":
          description: Internal Server Error
      tags:
      - users
  /users/send-otp:
    post:
      consumes:
      - application/json
      description: verify number with sms
      parameters:
      - description: phone number
        example: "+98123456789"
        in: body
        name: number
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'Ok. code: code_sent_to_number'
        "400":
          description: 'BadRequest:<br>code=number_delay: Wait some minutes.<br>code=invalid_field:
            a field is invalid'
        "500":
          description: Internal Server Error
      tags:
      - users
  /users/signup:
    post:
      consumes:
      - application/json
      description: Signup user. User must be verify number first.
      parameters:
      - description: phone number
        example: "+98123456789"
        in: body
        name: number
        required: true
        schema:
          type: string
      - description: full name
        example: test
        in: body
        name: name
        required: true
        schema:
          type: string
      - description: Token
        in: body
        name: token
        required: true
        schema:
          type: string
      - description: Password
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: 'BadRequest:<br>code=verify_number_first: User Must be verify
            number first<br>code=invalid_field: a field is invalid'
        "500":
          description: Internal Server Error
      tags:
      - users
  /users/verify-otp:
    post:
      consumes:
      - application/json
      description: verify number with sms
      parameters:
      - description: phone number
        example: "+98123456789"
        in: body
        name: number
        required: true
        schema:
          type: string
      - description: OTP code
        example: 12345
        in: body
        name: otp
        required: true
        schema:
          type: integer
      - description: Token
        in: body
        name: token
        required: true
        schema:
          type: string
      - description: verify mode
        example: '"signup" or "reset_password"'
        in: body
        name: mode
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "303":
          description: 'Success<br>Ok. code: go_reset_password <br>Ok. code: go_signup.
            verify number done. user must signup'
        "400":
          description: 'BadRequest:<br>code=go_send_otp_first: Must go to send-otp
            first.<br>code=wrong_otp: The OTP is wrong.<br>code=invalid_field: a field
            is invalid'
        "500":
          description: Internal Server Error
      tags:
      - users
swagger: "2.0"
